# Generated by Django 2.0.3 on 2018-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tweets', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=45)),
                ('place', models.TextField(null=True)),
                ('tweet', models.TextField(null=True)),
                ('dateTime', models.DateTimeField()),
                ('country', models.CharField(max_length=46)),
                ('text_lem', models.TextField(null=True)),
                ('sentiment_compound_polarity', models.FloatField(null=True)),
                ('sentiment_neutral', models.FloatField(null=True)),
                ('sentiment_negative', models.FloatField(null=True)),
                ('sentiment_pos', models.FloatField(null=True)),
                ('sentiment_type', models.CharField(max_length=47)),
            ],
            options={
                'verbose_name': 'Tweets',
                'ordering': ['dateTime'],
            },
        ),
    ]
