# Generated by Django 2.0.3 on 2018-04-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments_analysis', '0002_auto_20180409_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='id_tweets',
        ),
    ]
