# Generated by Django 2.0.3 on 2018-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments_analysis', '0003_remove_tweets_id_tweets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={},
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='sentiment_negative',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='sentiment_neutral',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='sentiment_pos',
        ),
        migrations.AddField(
            model_name='tweets',
            name='gender_predicted',
            field=models.CharField(max_length=47, null=True),
        ),
    ]
