# Generated by Django 2.0.3 on 2018-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments_analysis', '0004_auto_20180410_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='country',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='dateTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='gender_predicted',
            field=models.CharField(db_index=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='sentiment_type',
            field=models.CharField(db_index=True, max_length=45, null=True),
        ),
    ]
