# Generated by Django 2.0.3 on 2018-04-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments_analysis', '0005_auto_20180411_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
