# Generated by Django 2.0.3 on 2018-04-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiments_analysis', '0006_tweets_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='country_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
